### ISSUE TITLE
question: is ban-imports needed ?

### ISSUE THREAD

**Issue by Hotell** [cartant/eslint-plugin-etc#3]
Just curious, is there any difference between `ban-imports` and [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports) ? 

Thanks !

**Comment by cartant** [comment]
Just the config, I would imagine. The rule is so simple that I just converted it. I guess there could be some people, who have used the TSLint rule, that might find it simpler just to copy the existing rule config to the ESLint rule - rather than look up the configuration options for `no-restricted-imports`, etc.

ATM, the table in the README lists whether or not the rules are recommended as to-be-determined (TBD). When the conversions are done, I will have another look at the rules and whether there are built-in/official rules that doe the same or similar thing. In the case of `ban-imports`, I would anticipate that it would not be recommended and that the README will refer users to `no-restricted-imports`.

**Comment by Hotell** [comment]
thanks for thorough response Nicholas! makes sense. keep rockin' 💪
